### ISSUE TITLE
empty helpers folder in the solution branch

### ISSUE THREAD

**Issue by jsms90** [marisid/handlebars-intro-workshop#3]
Is it a kind of stretch goal to get onto this if you have time?
https://github.com/marisid/handlebars-intro-workshop/blob/completed-workshop/views/helpers/custom-helper.js

**Comment by marisid** [comment]
Good point @jsms90 but I'm not sure if we will have time for this one too (code alongs take longer than a walkthrough as you have to make sure all 16 people follow). I believe it's better to explain the basics well to an extent that all people feel confident with those and then move to the next level. 

It took me a while to understand what is an ideal or let's say typical folder structure for a server-side Handlebars set up - which in principle applies for most templating engines and is one of the main takeaways of this workshop. 

Also, they will be implementing a helper function on Tuesday morning during the morning challenge - so they will be exposed to this one too. How does that sound?

**Comment by marisid** [comment]
Just added an example of a helper function in a separate branch.

**Comment by jsms90** [comment]
@marisid All of that makes perfect sense. It's just that there is then no need for the empty folder and file.

Introducing blank files to your project is something I continually tell FAC10 not to do, that's all. So, not to be pedantic, but you do still have a blank `helper.js` file that never gets used for anything

**Comment by marisid** [comment]
@jsms90 yes understood - the only reason why I had an empty folder (and a containing empty file so that the folder is tracked with git) in the first place is so that I can show them the view folder configuration. 

If you find it confusing, I can remove it.
