### ISSUE TITLE
encourage use of {{!< layout/default}}

### ISSUE THREAD

**Issue by jsms90** [marisid/handlebars-intro-workshop#4]
Just a good idea to get them into the habit of providing useful comments like this, for the time when their projects are so big that they have multiple layout files :+1: 

Like in [this future studio tutorial](https://futurestud.io/tutorials/how-to-create-a-dynamic-handlebars-layout-template-in-hapijs)

**Comment by marisid** [comment]
Good shout - I'll point this out in the code along and I've added a comment too. ✔️
